### ISSUE TITLE
Inicio y registro de usuarios

### ISSUE THREAD

**Issue by pedroelfire** [EdgarQuinonez/nufogy-expo-app#1]
La patalla de inicio de sesion se mostrara al entrar a la aplicacion, la pantalla tiene que tener los siguientes puntos:

1. Un fondo blanco o cremita
- Los campos deberan estar centrados, con una leyenda en el input con su nombre respectivo, esta leyenda debera desaparecer al pulsarlos o escribir en ellos
- Arriba debera estar Usuario y abajo contraseña
- Deberan tener una linea negra abajo indicando que es donde se va a escribir, no ser recuadros
- Los campos de contraseña deben de tener un ojo para poder visiualizarla
2. Abajo debera tener un boton que te mande a la ventana de registro
3. Al iniciar sesion debera mandarte a la feed (Por ahora una ventana en blanco con una nav bar por debajo con 4 botones, Diario, Jack, Dietas, Perfil, cada uno con su respectivo icono)

![image](https://github.com/EdgarQuinonez/nufogy-expo-app/assets/88966740/a0dd5c83-5f73-41c4-8b21-dc6421e83610)

4. Al realizarse el inicio de sesion, se debera hacer un post en la ruta /api-token-auth con los datos del usuario de esta manera:
Payload
{
    "username": "DoctorJugetes",
    "password": "Doctor12345"
}
Response
{
    "token": "86d359d6df8e87bd62487e1f5183fb217138a89d"
}
El token se debera de guardar en el cache del dispositivo, y este token se mandara como parametro en las Heads de todos las request que se realizen (Mas informacion en la documentacion)
6. Abajo debe de haber una opcion para poder registrarse

Ejemplo de la ventana de Inicio de registro:
1.  Con una estructura similar a la del inicio de sesion, se añadira un input extra para confirmar contraseña, de manera que se tenga que escribir igual dos veces la contraseña
2. Debera indicar si la contraseña es muy débil
3. Tendra un boton abajo para regresar al inicio de sesion
4. Una vez iniciada la sesion, debera mostrar un dialogo con el texto "Cuenta creada exitosamente" y te debera regresar a la pantalla de inicio de sesion (Esto es temporal, luego se añadira una ventana para completar su registro de peso altura etc)
![image](https://github.com/EdgarQuinonez/nufogy-expo-app/assets/88966740/948d1320-51c6-4200-94c0-909454cc6ee8)

**Comment by EdgarQuinonez** [comment]
Ya quedó.
