### ISSUE TITLE
Funcionamiento de la ventana diario y mejoras generales

### ISSUE THREAD

**Issue by pedroelfire** [EdgarQuinonez/nufogy-expo-app#3]
Por motivos practivos, ahora se utilizara el siguiente usuario: Pedro10 password
Toda la documentación de la api se ingresara al final del documento

**Ventana DIARIO** 
1. Ahora las calorías del usuario se van a calcular de manera automática en base a la información de su perfil, para calcular las calorías referirse al siguiente código de calculadora de calorías del IMSS donde se tiene la misma estructura de datos 
[calculadora-calorias.txt](https://github.com/user-attachments/files/16286069/calculadora-calorias.txt)

2.Calcular los macro nutrientes

3. Mostrar las ventanas de "Meal Types (Desayuno, Comida, Cena, Colacion 1, Colacion 2)" en la ventana diario, las mealtypes de cada usuario por defecto son Desayuno comida y cena, pero se pueden tener hasta 5 y tener el nombre que le designe el usuario, para obtenerlas hacer un GET a https://nufogy-api.fly.dev/diary/mealtype, la id de la mealtype sera utilizada para guardar un registro en el diario, y cada mealtype se mostrara o no dependiendo de su estado de "active"

4. Ahora se crearan registros al buscar un ingrediente y guardarlo, lo cual debera generar un POST a https://nufogy-api.fly.dev/diary/logs/ como el siguiente (Cada que se da a guardar un ingrediente se debera generar esta solicitud): {
    "fs_id": "5050",
    "meal_type": "10",
    "metric_serving_amount": "100",
    "metric_serving_unit": "Gr",
    "date": "2024-07-18"
}

5. Para obtener las comidas ya registradas del usuario, hacer un GET a https://nufogy-api.fly.dev/diary/logs/ lo cual regresara (Las calorias y macros se calcularan desde el cliente):
 [
    {
        "user_id": 24,
        "fs_id": 5050,
        "metric_serving_amount": 100.0,
        "metric_serving_unit": "Gr",
        "meal_type": 10,
        "date": "2024-07-18"
    }
]

**Mejoras Generales**
1. El botón de la paloma arriba, no hace nada, quitarlo
![Imagen de WhatsApp 2024-07-18 a las 00 00 17_5ddfbb9e](https://github.com/user-attachments/assets/b856537f-3e15-468d-81f6-a52dc8d047a0)

2. Agregar el teclado con botón de cancelar o listo para iPhone y si hay, en Android
Como se ve:
![Imagen de WhatsApp 2024-07-18 a las 00 00 14_77615503](https://github.com/user-attachments/assets/03872c3c-3a4d-44fe-8f0a-0c6895a04792)

Como se debería ver:
![capturas-de-pantalla-de-u-c7aa8c77b834b](https://github.com/user-attachments/assets/e849e151-a777-4ce1-a9a3-7efd7aa592c9)

**Comment by EdgarQuinonez** [comment]
Quedó todo completado.
